### ISSUE TITLE
License MIT?

### ISSUE THREAD

**Issue by Tortoise17** [sign-language-processing/sign-gpt#1]
Please kindly include the license terms and conditions for the current repo.

**Comment by AmitMY** [comment]
A license will be included once this repository has some code.
At the moment there is no code

**Comment by Tortoise17** [comment]
@AmitMY Until when will be code available?

**Comment by AmitMY** [comment]
This was more of an idea, and not yet an active project by myself.

**Comment by Tortoise17** [comment]
Great, I have just started looking into this domain from your other repos. But once I have gone through all, I will let you know and will be helpful gladly if I could.
